version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=5
    network_mode: host

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=localhost:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOOP_PERIOD=10s
    network_mode: host
    depends_on:
      - server